trigger:
- development

pool:
  name: Stan Pool 

variables:
  buildDir: 'build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn run build
  displayName: 'yarn install and build'

# Zip build folder
- script: |
    echo "List all files/folders in current working directory:"
    ls -la
    echo "List contents of dist directory:"
    ls -la dist || echo "dist folder does not exist"
  displayName: 'Check if dist folder is created'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    replaceExistingArchive: true
  displayName: 'Archive build output'

# Publish as artifact (optional but useful for release pipelines)


# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-sub-conn'
    appType: 'webApp' # or 'webApp' for Windows
    appName: 'erc20-ui-dev'
    package: '$(Build.ArtifactStagingDirectory)/build.zip'
  displayName: 'Deploy to Azure Web App'
