trigger:
- development

pool:
  name: Stan Pool 

variables:
  buildDir: 'build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo Starting yarn install and build
    yarn install || exit /b 1
    yarn run build || exit /b 1
  displayName: 'Install and Build Vite React App (Windows)'

- script: |
    echo === Current working directory ===
    cd
    echo === List root directory ===
    dir
    echo === List contents of dist (should exist if build succeeded) ===
    if exist dist (
      dir dist
    ) else (
      echo ❌ dist folder NOT FOUND
      exit /b 1
    )
  displayName: 'DEBUG: Check dist folder on Windows'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    replaceExistingArchive: true
  displayName: 'Archive build output'

# Publish as artifact (optional but useful for release pipelines)


# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-sub-conn'
    appType: 'webApp' # or 'webApp' for Windows
    appName: 'erc20-ui-dev'
    package: '$(Build.ArtifactStagingDirectory)/build.zip'
  displayName: 'Deploy to Azure Web App'
