trigger:
- development

pool:
  name: Stan Pool 

variables:
  buildDir: 'build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    set -e
    yarn install
    yarn run build
  displayName: 'yarn install and build'

- script: |
    echo "=== Current working directory ==="
    pwd
    echo "=== List root ==="
    ls -la
    echo "=== List contents of ./dist (should exist if build succeeded) ==="
    ls -la dist || echo "❌ dist folder NOT FOUND"
  displayName: 'DEBUG: Check dist folder existence'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    replaceExistingArchive: true
  displayName: 'Archive build output'

# Publish as artifact (optional but useful for release pipelines)


# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-sub-conn'
    appType: 'webApp' # or 'webApp' for Windows
    appName: 'erc20-ui-dev'
    package: '$(Build.ArtifactStagingDirectory)/build.zip'
  displayName: 'Deploy to Azure Web App'
